### ISSUE TITLE
Make a new antic release?

### ISSUE THREAD

**Issue by fingolfin** [flintlib/antic#41]
It would be great if there was a new antic release with the changes since 0.2, and which depends on Flint 2.6.0

See also #31 and https://github.com/JuliaPackaging/Yggdrasil/pull/1142.

**Comment by wbhart** [comment]
Agreed. Would be good if people could make a list of things that they want from the release, other than clarifying the license text in all the files (which I already know about).

Releases are pretty informal. I just tag one when people think it is ready. Antic is not a huge library.

I should point out there are essentially zero new features since the last release. All the development has been done on top of antic in Hecke.

**Comment by wbhart** [comment]
Perhaps @fredrik-johansson and @tthsqe12 have some specific requirements (which are not multi-year research projects).

**Comment by tthsqe12** [comment]
No requirements from me. I have only been trying Hecke.

**Comment by fredrik-johansson** [comment]
I have no feature requests right now.

**Comment by wbhart** [comment]
Well then I propose we fix the license in the files and tag 0.2.1. That should maximally piss off the people who expect at least a new minor version number for the change in license.

**Comment by wbhart** [comment]
Done.
