### ISSUE TITLE
nf_elem_set_fmpq_poly is unsafe

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/antic#54]
As presently implemented nf_elem_set_fmpq_poly only works correctly if the input polynomial is already reduced (which is not checked).

In a general number field, it creates an unreduced nf_elem which is probably not what the user expects. More seriously, in a linear or quadratic field it will just throw away the high coefficients and thus silently produce nonsense.

**Comment by tthsqe12** [comment]
Yes, this is a problem. @wbhart can you fix it soon.

If the input to `nf_elem_set_fmpq_poly` is supposed to be reduced, then I have to reduce modulo the modulus myself. However, there is no function for getting the modulus (i.e. `nf_get_modulus(fmpq_poly_t, const nf_t)`)!

It would of course be best if the `nf_elem_set_fmpq_poly` just did the correct thing. And, it is probably a good idea to have `nf_get_modulus` anyways, or a `nf_modulus_ref` returning a `const fmpq_poly_struct *` if this is possible.

**Comment by wbhart** [comment]
Thanks for reminding me. Yes, I will try to address this after the meeting today.

**Comment by wbhart** [comment]
The problem here is that we don't really have a function to reduce an *arbitrary* polynomial modulo the defining polynomial. An unreduced poly with respect to Antic has a particular meaning, namely a product of two reduced polynomials. (And in the case of a linear polynomial defining I don't even think we allow that.)

I can fix it so that this function accepts an unreduced polynomial in that sense. But making it accept an arbitrary polynomial is rather a lot of work.

I can of course make it complain if the polynomial is too large for our reduction code. Is this sufficient?

**Comment by tthsqe12** [comment]
> I can of course make it complain if the polynomial is too large for our reduction code. Is this sufficient?

No. It has to accept all inputs. If this is a performance critical function, how about putting the current inline code into `_nf_elem_set_fmpq_poly_reduced` and then remove the inline from `nf_elem_set_fmpq_poly` :
```
if input->length < n
    use existing _nf_elem_set_fmpq_poly_reduced
else if input->length < 2*n-1
    use existing double length reducer
else
    use fmpq_poly_rem // doesn't have to be fast, just correct
```

**Comment by wbhart** [comment]
If you don't care about speed, I guess I can use fmpq_poly_rem. Hopefully that actually does the same thing.
